name: 'Github Actions Secret Workflow'

on:
    workflow_dispatch:

jobs:
    deployment:
      runs-on: ubuntu-latest
      
      steps:
        - name: 'Accessing Secrets'
          run: |
            echo "Secret from GitHub Actions: ${{ secrets.MY_TOP_PASSWORD }}"
            echo "i_dont_exist: ${{ secrets.i_dont_exist }}"


        - name: 'Print secret environment variable
          run: |
            echo "MY_TOP_PASSWORD: $MY_TOP_PASSWORD"'
          env:
            MY_TOP_PASSWORD: ${{ secrets.MY_TOP_PASSWORD }}
           